server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: bonobo
    url: jdbc:postgresql://localhost:5432/bonobo
    username: bonobo
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  mail:
    host: localhost
    port: 1025
    username: bonobo
    password: bonobo-best-monkey

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000